apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sre-agent

resources:
  - ../../base

nameSuffix: -prod

patchesStrategicMerge:
  - configmap-patch.yaml
  - replica-patch.yaml
